
// my IOCTL command
#define MYMEMDEV_IOC_MAXNR			3
#define MYMEMDEV_IOC_MAGIC 			'k'
#define MYMEMDEV_IOC_GETDATA 		_IOR(MYMEMDEV_IOC_MAGIC,1, int)
#define MYMEMDEV_IOC_SETDATA 		_IOW(MYMEMDEV_IOC_MAGIC,2, int)
#define MYMEMDEV_IOC_PRINT 			_IO(MYMEMDEV_IOC_MAGIC,3)
